### ISSUE TITLE
Problem with JIGSAW

### ISSUE THREAD

**Issue by IamMRM** [nzl-thu/MUSDL#1]
When trying to run with Jigsaw data, the code gives error of No CUDA devices available and on line in main.py of JIGSAW

i3ds = nn.ModuleList([InceptionI3d() for _ in range(4)]).cuda()

Although Cuda is using Nvidia Tesla from Colab and is enabled. The same environment was able to run with other dataset.

**Comment by nzl-thu** [comment]
Please try changing the gpu arguments in bash command. For example, try the following command:

python -u main.py --cls Knot_Tying --type USDL --gpu 0,1

If Colab has more than 1 gpu available, then the above command should work:)
